---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mm-custom.fullname" . }}
  labels:
    {{- include "mm-custom.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mm-custom.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mm-custom.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mm-custom.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: matchfunction
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.matchfunction.image.repository }}:{{ .Values.matchfunction.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: grpc
              containerPort: {{ .Values.matchfunction.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: grpc
          readinessProbe:
            httpGet:
              path: /
              port: grpc
          resources:
            {{- toYaml .Values.matchfunction.resources | nindent 12 }}
      {{- with .Values.matchfunction.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.matchfunction.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.matchfunction.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
