apiVersion: v2
name: nakama
description: A Helm chart for Nakama open source game server.
type: application
version: 0.2.1
appVersion: "3.22.0"


dependencies:
- name: postgresql
  version: "15.5.14"
  repository: "https://charts.bitnami.com/bitnami"
  condition: postgresql.enabled
- name: cockroachdb
  version: "13.0.2"
  repository: "https://charts.cockroachdb.com/"
  condition: cockroachdb.enabled
